### ISSUE TITLE
Create set of Polkadot.js test scripts

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#1198]
## Expected Behavior

- Scripts should list each of the available Polkadot.js methods and have an example of executing each of the call

-

## Current Behavior

-

## Possible Solution

-

## Steps to Reproduce

1.
2.
3.
4.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
potentially related to #838 #839

**Comment by edwardmack** [comment]
Polkadot.js builds it's api dynamically based on the functionality of the current runtime wasm.  The functions available are presented in the metadata for the runtime.  So, we can't just build a set of scripts to test Polkadot.js since the api will change based on the runtime, instead we need to dynamically build the test scripts based on the runtime's metadata.  Polkadot.js apps does this when determining how to construct the UI.
