### ISSUE TITLE
dot/state: store trie nodes individually in database

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1343]
## Task summary

- currently, once a block is imported, the entire state trie is encoded and stored in the database at the root hash as the key
- this is very inefficient since most of the keys don't change between blocks
- instead, the trie should be stored in the database by trie node
- key = hash of trie node; value = encoded trie node
- this way, the trie can be recursively reconstructed by looking up its root hash, decoding the trie node from there, and then looking up its children nodes by hash, and so on until the trie in reconstructed
- to update a trie value, only the node that is updated and its parents up to the root need to be updated

Note: trie node keys in database should be prefixed by some prefix (`trie` perhaps) to allow for the keys to have improved locality within the database

need to implement the following:
```
type Trie interface {
     // Store stores each trie node in the database, where the key is the hash of the encoded node and the value is the encoded node. Generally, this will only be used for the genesis trie.
     Store(db chaindb.Database) error

     // Load reconstructs the trie from the database from the given root hash. Used when restarting the node to load the current state trie.
     Load(db chaindb.Database, root common.Hash) error

     // PutInDB puts a value into the trie and writes the updates nodes the database. Since it needs to write all the nodes from the changed node up to the root, it writes these in a batch operation.
     PutInDB(db chaindb.Database, key, value []byte) error 

     // DeleteFromDB deletes a value from the trie and writes the updated nodes the database. Since it needs to write all the nodes from the changed node up to the root, it writes these in a batch operation.
     DeleteFromDB(db chaindb.Database, key []byte) error

     // ClearPrefixFromDB deletes all keys with the given prefix from the trie and writes the updated nodes the database. Since it needs to write all the nodes from the changed node up to the root, it writes these in a batch operation.
     ClearPrefixFromDB(db chaindb.Database, key []byte) error

     // GetFromDB retrieves a value from the trie using the database. It recursively descends into the trie using the database starting from the root node until it reaches the node with the given key. It then reads the value from the database.
     GetFromDB(db chaindb.Database, key []byte) ([]byte, error)
}
```

``` 
// StorageState is used to read and write storage tries from the database, as well as read storage values given a root hash.
// It should also store the current storage root at a database key. 
type StorageState struct {
    db chaindb.Database 
    currentTrie Trie // the current storage trie at the chain head
}

type StorageState interface {
    // Loads the current trie from the database by first reading the current storage root from the db, then reconstrucitng the trie. 
    LoadCurrentTrie() error 

     // Get returns a storage value given the trie root hash. It recursively descends into the trie using the database starting from the root node until it reaches the node with the given key. It then reads the value from the database.
    Get(root common.Hash, key []byte) ([]byte, error)

    // NewRuntimeStorage returns a new RuntimeStorage from the given storage root.  If the root is the current root, it uses the trie cached in the StorageState after copying it; otherwise, it (optionally) loads it from the database. (note: may not be needed to load the entire trie, could just pass in the database.)
    NewRuntimeStorage(root common.Hash) RuntimeStorage
}
```

```
type RuntimeStorage type {
      db chaindb.Database
      trie Trie
}

// RuntimeStorage is the interface used by the runtime to read and write the storage.
type RuntimeStorage interface {
      // Same as current runtime.Storage interface
}
```

see https://github.com/ChainSafe/gossamer/pull/1341 for preliminary benchmarking

**Comment by drskalman** [comment]
The main reason we use a trie is to deal with this. If you store the state root from the block under the block hash and retrieve it when you are changing the storage state to the state corresponding to that block, then the tree with the block state root has the state corresponding to that block and you have re-used all sub-trees which include the keys that are not changed. hence you are only have to store extra m x log(n) nodes  (where n is the number of all keys and m is number of changed keys) node for each block. That is the whole point of using a trei whose keys depends on the values the node holds. You don't need to use a another measure like timestamp to implement this.

**Comment by noot** [comment]
issue description updated!

**Comment by arijitAD** [comment]
**Problem**: Currently we do **Deepcopy** of Trie which is not the efficient way to copy the Trie.

**Solution**: We can implement a [persistent data structure](https://en.wikipedia.org/wiki/Persistent_data_structure#Persistent_hash_array_mapped_trie) that maintains every version of the Trie in the same trie.
<img width="712" alt="Screenshot 2021-02-01 at 7 33 17 PM" src="https://user-images.githubusercontent.com/5843604/106496421-e1e1f300-64e2-11eb-986f-114ce932fe1e.png">

Chainsafe already has an implementing to the persistent trie in JS. ([https://github.com/ChainSafe/persistent-merkle-tree](https://github.com/ChainSafe/persistent-merkle-tree)) We can port that to Golang.

**Problem**: How do we handle deletes in case of the above trie since a node can be shared among multiple version?

**Solution**: I looked into other trie implementing and one of the ways to do it is to implement reference counting at the node using an atomic variable.

[https://www.youtube.com/watch?v=WT9kmIE3Uis](https://www.youtube.com/watch?v=WT9kmIE3Uis)

**Problem**: How do we figure out which leaf nodes are modified in the current trie so that we only store modified nodes in DB?

**Solution**: 

1. Store a bloomfilter at root and update it whenever data is written.
2. Add logical timestamp at root and every leaf node. 

    If TS(Root) < TS(Node) then the data has been updated.

This paper implements a presistent trie with timestamping. It does O(1) snaphot.

[http://aleksandar-prokopec.com/resources/docs/ctries-snapshot.pdf](http://aleksandar-prokopec.com/resources/docs/ctries-snapshot.pdf)

Golang Implementation of Ctrie: [https://github.com/Workiva/go-datastructures/blob/master/trie/ctrie/ctrie.go](https://github.com/Workiva/go-datastructures/blob/master/trie/ctrie/ctrie.go)

**Comment by arijitAD** [comment]
Created a ticket to implement persistent trie and benchmark it. #1349
