### ISSUE TITLE
 author_submitAndWatchExtrinsic: handle extrinsic status future and ready

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#1535]
## Task summary

- RPC [author_submitAndWatchExtrinsic](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#189-author_submitandwatchextrinsic-pubsub) defines status "future" and "ready" for when extrinsic is added to future and ready queue.  These status notifications need to be implemented.
- cross reference what ready status means in substrate
- check if the future queue is really a hashmap

## Specification reference

- see https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#189-author_submitandwatchextrinsic-pubsub
- Around line 302 in dot/rpc/subscription/websocket.go

## Other information and links

-

**Comment by EclesioMeloJunior** [comment]
Hi @edwardmack, actually we don't know when an extrinsic is added into a `ready` or `future` queue, right? Or there is some way to get this information?

I saw that `HandleSubmittedExtrinsic` if `s.isBlockProducer` is true, adds the extrinsic to the pool, is this related to the `ready` or `future` queue? what happens if it's not a block producer?

**Comment by EclesioMeloJunior** [comment]
> what happens if it's not a block producer?
I realized that if it is not a block producer, there is no need to add the transaction in the pool, sorry.

**Comment by noot** [comment]
we still need to add it to the pool if we're not a block producer, that code in dot/core should be removed
