### ISSUE TITLE
dot/network: check if peer supports protocol before sending message

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1571]
## Task summary

- currently we don't check if a peer supports a given protocol before attempting to open a stream with them/send a message over that stream
- this results in an error
- we should check before doing this that the peer supports the given protocol

**Comment by danigomez** [comment]
Hi!, for this issue each time that an attempt to open a `NewStream` (Like in https://github.com/ChainSafe/gossamer/blob/f195204ca0e427c9dad09794955a002006fd8a8d/dot/network/host.go#L271) is done an error should be returned right away if the protocol is not supported wihout attempting a connection to the peer?? I think that at least a connection to that peer should be tried in order to know if a protocol is supported or not, right??

**Comment by noot** [comment]
@danigomez hey, sorry for the late reply. at the point `NewStream` is called there is already a connection established. this issue is specifically for the `sendData` function in `notifications.go` as this is the only function where outbound data is sent. essentially we want to check supported protocols before opening a stream with the remote peer in that function

**Comment by noot** [comment]
also @danigomez we have a team member scheduled to work on this, so if you have already started on this please let us know ASAP

**Comment by danigomez** [comment]
@noot no prob!. Let me know if there is any pending issue that i can work on. Thanks!
