### ISSUE TITLE
Use a map to search nodes in the blocktree.

### ISSUE THREAD

**Issue by arijitAD** [ChainSafe/gossamer#1604]
## Issue summary

- Use a map to search nodes in the block tree instead of iterating over the entire tree.
- Block tree can be redesigned to optimized operations. 

## Other information and links

- https://github.com/ChainSafe/gossamer/blob/be3c325ac5ad3031a0ee9b89d1c32edc4a7da9bd/lib/blocktree/blocktree.go#L153

**Comment by danigomez** [comment]
Hi!
I'm thinking in two approaches to solve this:

1. Each time a `getNode` is called, save the reference of the found node in a dictionary `map[Hash]*node`, so the next time `getNode` is called you can get the reference directly from the map, the problem with this is that you have to traverse the whole tree if the node is nor already in the dictionary
2. Once the blocktree is loaded (I think that is done in here https://github.com/ChainSafe/gossamer/blob/8c67795640855b0f1bfea1f5c3aa579f728d07d7/dot/state/service.go#L119), build a dictionary with all the nodes in the tree at startup, so when you call `getNode` you can directly get the node from the map.
I think that this is a better approach because you need to traverse the tree only once and keep the dictionary in sync with the updates in the tree.

Let me know if this makes sense to you.
Thanks!

**Comment by EclesioMeloJunior** [comment]
Good options @danigomez! @arijitAD @noot  the second option (load all the nodes on the map) could increase the gossamer node memory usage? I think that, instead of building a map with all the nodes at startup, we could save a fixed amount of them and the `getNode` function acts as a cache:

1) First try to get the node in the map if founds then return
2) Otherwise search for in the block tree and then save it in the map

**Comment by noot** [comment]
option 1 or what @EclesioMeloJunior proposed would be good since the blocktree will always be changing with each finalized block (ie. getting pruned) also, you will need to make sure when `blocktree.Prune` is called that the pruned nodes are cleared from the map
