### ISSUE TITLE
update wasmtime interpreter to work with runtime v0.9

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1658]
## Task summary

- update wasmtime ext_ functions to be compatible with v0.9
- add tests for all exported functions

**Comment by FlorianFranzen** [comment]
There are still some v0.8 functions missing, e.g. `

**Comment by noot** [comment]
@FlorianFranzen yes, the wasmtime interpreter is very out of date. thanks for the tracking, will be sure to add all those functions

**Comment by edwardmack** [comment]
There seems to be an issue with values being passed from the `inst.Exec()` to the receiving import function.
For example, in wasmtime test Test_ext_storage_set_version_1, the values I'm seeing for keySpan and valueSpan in imported func ext_storage_set_version_1 is 1, I don't expect these to be the same, and they shouldn't be 1.  So, I think that there may be an issue when the call is being constructed in wasmtime/instance.go in exec.

I get similar behavior when testing  Test_ext_hashing_blake2_128_version_1 and Test_ext_crypto_ed25519_sign_version_1.  I'm not able to lookup values in memory because it seems that wrong pointers are being sent to the import functions.

Example code is pushed to branch `ed/wasmtime_runtime_v09`

**Comment by danforbes** [comment]
@noot do you want to keep this Issue open or do you think we can close it since it seems like we are going to focus on Wasmer and/or Life for the time being?

**Comment by noot** [comment]
closing as we aren't focusing on wasmtime right now
