### ISSUE TITLE
concurrent trie writes of snapshotted trie cause unintended trie modifications

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1702]
## Describe the bug

- there are 2 processes that make updates to the state trie: `sync` and `babe`
- when there 2 processes concurrently write to the trie, it results in unexpected trie modifications, resulting in `Storage root mismatch` errors in `sync`, `Timestamp must be updated once in a block` in `babe`, and eventually a panic in the storage state `TrieState` due to a trie having an unexpected root
- this happens even though the trie is snapshotted in `state.StorageState.TrieState` 
- it happens even when the tries being modified are not snapshotted from the same trie (ie. parent root is different)

## Expected Behavior

- snapshotted trie should be concurrency safe

## To Reproduce
Steps to reproduce the behaviour:

if `https://github.com/ChainSafe/gossamer/pull/1700` is merged, then comment out the `storageState.Lock()` and  `defer storageState.Unlock()` in babe and sync

1. modify `gssmr/genesis-spec.json` to have 2 block producing nodes (and 2-3 grandpa authorities, although it's not necessary)
2. `./bin/gossamer --key alice --basepath /tmp/alice`, once alice builds a block, then start bob: `./bin/gossamer --key bob --port 7002 --basepath /tmp/bob`
3. wait for node panic 

## Log output

```
CRIT[07-21|12:39:14] [ext_logging_log_version_1]              pkg=runtime module=go-wasmer target=runtime message="panicked at 'Timestamp must be updated once in the block', /home/elizabeth/substrate/frame/timestamp/src/lib.rs:170:13" caller=imports.go:137
WARN[07-21|12:39:14] failed to handle slot                    pkg=babe slot=542295184 error="cannot finalise block: Failed to call the `BlockBuilder_finalize_block` exported function." caller=babe.go:429
panic: trie does not have expected root

goroutine 450 [running]:
github.com/ChainSafe/gossamer/dot/state.(*StorageState).TrieState(0xc000216600, 0xc0007ad2e8, 0x14, 0xc000128a60, 0x2)
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/dot/state/storage.go:164 +0x68b
github.com/ChainSafe/gossamer/dot/sync.(*Service).handleBlock(0xc000217c80, 0xc0112293b0, 0x10, 0xc000128420)
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/dot/sync/syncer.go:325 +0x277
github.com/ChainSafe/gossamer/dot/sync.(*Service).ProcessBlockData(0xc000217c80, 0xc0112dfb40, 0x1, 0x2, 0x4, 0x4, 0xc000eda480)
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/dot/sync/syncer.go:269 +0x615
github.com/ChainSafe/gossamer/dot/network.(*syncQueue).handleBlockData(0xc008140000, 0xc0112dfb40, 0x1, 0x2)
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/dot/network/sync.go:767 +0x4ce
github.com/ChainSafe/gossamer/dot/network.(*syncQueue).processBlockResponses(0xc008140000)
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/dot/network/sync.go:711 +0x15b
created by github.com/ChainSafe/gossamer/dot/network.(*syncQueue).start
	/home/elizabeth/go/src/github.com/ChainSafe/gossamer/dot/network/sync.go:179 +0xab
```

**Comment by arijitAD** [comment]
When we start two-node A and B, both nodes are creating a block x(same block num). Node A creates the block first and announces it to node B while block building of Node B is still in progress. So Node B tries to parallelly import the block and this changes the trie in runtime. When the block production of Node B is done it calls finalize block which errors out since the trie has been changed by the sync service.
To resolve this issue either,
1. (Costly)We can create a temporary instance of runtime and perform the operation on it. So that syncing and production are working on their own runtime.
2. (Recommended) We take a lock on the VM so that parallel sync and block production is not executed. Parallel execution of sync and produce only happens at the head so the lock won’t affect the syncing process. (This is currently done)

**Comment by noot** [comment]
closing this for now as it's been resolved for the current moment
