### ISSUE TITLE
rpc: update `author_insertKey` and `core.InsertKey()` to take into account keystore type

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1850]
## Task summary

- currently `author_insertKey` does not correctly use the `Type` parameter, which should correspond to a keystore type (not a key type)
- need to also update `core.InsertKey()` to insert key into correct keystore

## Specification reference

- https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#185-author_insertkey
https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#1811-key-types

**Comment by kishansagathiya** [comment]
> currently author_insertKey does not correctly use the Type parameter, which should correspond to a keystore type (not a key type)

Can you clarify this? `Type` parameter is string in KeyInsertRequest, which as mentioned in the spec. It's meaning also seems as expected. I don't see the code using/assuming `Type` to be `crypto.KeyType`, instead of `keystore.Type()` (babe, gran, etc). 
I don't see the problem, yet. What am I missing?
