### ISSUE TITLE
Implement memory management for ext_malloc, ext_free

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#191]
We need to implement malloc and free external wasm calls. See section `E.2` in the [spec](https://github.com/w3f/polkadot-re-spec/blob/master/polkadot_re_spec.pdf).

Seems Substrate has a Freeing Bump Heap implementation: https://github.com/paritytech/substrate/blob/b6c2180d3e438e2a2b2df6620ba3ee71a0174fe7/core/executor/src/allocator.rs which is used here: https://github.com/paritytech/substrate/blob/4dc625ffd5dacfa4143a735ca0d13a69c367c46d/core/executor/src/wasm_executor.rs

**Comment by noot** [comment]
Relevant issue: https://github.com/paritytech/substrate/issues/1615

**Comment by edwardmack** [comment]
I've just done a "draft" PR.  The code is working, but I have some points I'd like to discuss, so I did PR for your review.  The main question has to do with differences in the way the WASM heap is handled.

- In the substrate implementation they are using a WASM interpreter (https://github.com/paritytech/wasmi) that exposes different functions for handling the WASM heap including
  - `Memory.used_size()` which is used to calculate pointer offset.
  - `MemoryInstance::alloc()` to initialize the WASM heap to a given size.
- The  WASM interpreter that we're using doesn't expose these types of functions to the WASM heap.  It basically exposes the heap as a slice, then we use go functions to manage it.  This is fine, except that there is no function to determine how much of the heap is used before the allocator is initialized.  And it seems that we don't have as much control over heap allocation (size). So....
- Some of the tests in the substrate code depend on the heap being in a specific state (size, about used) before the test is run.
  - `TestAllocatorShouldAlignPointersToMultiplesOf8` fails because it expects a pointer of 24 (offset by 16 during allocator construction based on used memory).  But it does return the expected multiple of 8.
  - `TestShouldAllocateMaxPossibleAllocationSize` fails because we can't grow the heap's memory before the allocator is initialized (or at least I don't know how to).

In general I think the code is doing what it should, but I wanted to discuss this with someone.

Looking forward to your thoughts regarding this, and your comments regarding my code.

**Comment by edwardmack** [comment]
For some insight passing pointer in go/cgo: https://stackoverflow.com/a/38748361/11942076
