### ISSUE TITLE
Profile memory usage and describe plan of action to address issues

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#1936]
## Issue summary

- Profile nodes on staging, gossamer devnet, locally to identify root cause of memory issues
- After a certain block height the node becomes unresponsive
- One contributing factor could be the node.deepCopy 
- Outline a plan of action to address the memory issues

## Other information and links

- some work has already been done regarding this in the parent epic https://github.com/ChainSafe/gossamer/issues/1494

**Comment by arijitAD** [comment]
https://drive.google.com/drive/folders/1eh5_0Kb4zbwe8qckCqJ2we6EE3nTkr4C?usp=sharing
Investigate memory consumption in the Trie.

**Comment by qdm12** [comment]
With #2009 memory consumption (`RES`) grows until it stabilizes and oscillates between 9.2 and 9.8GB, after several hours (depends on CPU speed). I'll investigate if they are obvious ways to reduce memory usage in the rest of the code in the coming days according to the plan outlined above.

**Comment by qdm12** [comment]
Problem is definitely coming from https://github.com/ChainSafe/gossamer/blob/ccf12dec1344e9ff827bca43546e33c9c0476d30/lib/trie/trie.go#L72-L82

We are appending hashes of 'old generation node' to the `deletedKeys` hash slice, but these are actually still referenced by their parent branch (unless it's the root).

One way to fix this would be to keep a reference to the parent branch (or nil for the root node) in order to clear the reference to the node being from the older generation.

I am still reviewing and testing the code in `lib/trie/trie.go` to see if this is possible and to find the best way to do so without breaking another feature.

**Comment by qdm12** [comment]
After full unit testing coverage and full linear refactoring of `trie.go`, the comment above is actually wrong. Although there were some misuses of the snapshotting mechanism in certain places of the code, which were causing some minor memory leaks.

Most notably, the following issues were the root of the memory usage increasing over time:

### Issues fixed during the trie refactoring

- Minor memory leak fixes due to bad logic (regarding generation mostly)

### Issues fixed by refactoring the trie node code

- Sync.Pool memory leak due to buffers not being placed back into the buffer pool

### Issues fixed in `dot/state`

- Fix prune keys being empty, to remove unfinalized tries once a trie is finalized
- Fix `sync.Map` not allowing proper garbage collection when a key is deleted, for the map from root hash to trie
- Fix removing the previous finalized trie when finalizing a trie

**Comment by qdm12** [comment]
There is a memory leak with the gossip map of seen hashes, discovered in https://github.com/ChainSafe/gossamer/pull/2383

**Comment by qdm12** [comment]
Gossip map of seen hashes memory leak mentioned above is tracked by #2398 (found in audit)

**Comment by timwu20** [comment]
Closed since we have resolved a lot of our slow memory leaks.  Also will be revamping state storage, so another round of testing will be done.
