### ISSUE TITLE
fix DHT connection on discovery on devnet

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#2026]
## Task summary

- DHT discovery seems to have regressed on the devnet and no longer works
- previously, when running 3 nodes Alice, Bob and Charlie, Bob and Charlie would use Alice as their bootnode, and then discover each other via the DHT, resulting in each node having 2 peers
- however it seems to have regressed w/ the peer scoring update and this no longer happens (Alice has 2 peers, but Bob and Charlie only have 1, and they no longer connect to each other)
- it seems they still discover each other, but don't connect to each other, as adding in code to directly connect them after discovering results in the correct behaviour (ie. adding a line here to connect them, as can be seen in older commits)
https://github.com/ChainSafe/gossamer/blob/d7147cf4048de2ac41f5ef27462c20b10d4fe28f/dot/network/discovery.go#L212-L221

**Comment by kishansagathiya** [comment]
This has to do with the IP address that we are using. `network/host.go` has code that gets public IP of the machine and create multi address from that IP. It also has code that removes private IPs from `host.Addr()`.

Since most devices are behind NAT, we cannot use just public IP. We need the IP that is used for NAT mapping by the router.

Currently, the code works if bootnode is not behind NAT.
