### ISSUE TITLE
 build staking transcation ?

### ISSUE THREAD

**Issue by LXHLeaner** [ChainSafe/gossamer#2859]
how to use this to build a staking transcation?

**Comment by danforbes** [comment]
This project would not be suitable for building a staking transaction - Gossamer is a [Polkadot Host](https://wiki.polkadot.network/docs/learn-polkadot-host), which is the client infrastructure that executes the runtime of a Polkadot-like network such as Westend, Kusama, or Polkadot. If you're looking to build a staking transaction in Go, you may want to check out the [Centrifuge Substrate Go API](https://github.com/centrifuge/go-substrate-rpc-client). There is also [a Javascript library](https://polkadot.js.org/docs/api/examples/promise/make-transfer) that can help you do the same. If you're just looking to submit a staking transaction, you can check out [this tutorial](https://www.youtube.com/watch?v=FCXC0CDhyS4) that will teach you how to do so using a web frontend. I'm going to close this Issue since it's not relevant to this repository, but please feel free to follow up with any questions if you have them. You can also ask on the [Substrate Stack Exchange](https://substrate.stackexchange.com/).
