### ISSUE TITLE
VRF

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#293]

**Comment by thomasmodeneis** [comment]
what is the objective with this epic ?

**Comment by noot** [comment]
@thomasmodeneis this epic is for implementing the VRF functions needed for BABE. however, this is currently blocked since we haven't yet had success using w3f/schnorrkel as a library for gossamer, since it's in rust.
we are looking to eventually do an alternative implementation of schnorrkel VRFs in pure go. we have already started writing some of schnorrkel in go here, but it only has keys and signing so far. https://github.com/ChainSafe/go-schnorrkel
