### ISSUE TITLE
Adding support for using locally provided runtime

### ISSUE THREAD

**Issue by radkomih** [ChainSafe/gossamer#3010]
## Issue summary

Hi, I am using a fork of Gossamer for running tests by providing local runtime instead of fetching a remote one. I am using the fork only because of this snippet:
```go
// NewLocalTestInstanceWithTrie ...
func NewLocalTestInstanceWithTrie(t *testing.T, runtimeFilepath string, tt *trie.Trie) *Instance {
	t.Helper()

	cfg := setupConfig(t, tt, DefaultTestLogLvl, common.NoNetworkRole, runtimeFilepath)

	r, err := NewInstanceFromFile(runtimeFilepath, cfg)
	require.NoError(t, err)
	return r
}
```
Is it an option for you to integrate it into the official Gossamer?

Thanks!

**Comment by q9f** [comment]
Hi, which fork is that?

**Comment by radkomih** [comment]
It is this one https://github.com/LimeChain/gossamer, but the only difference is the above snippet (and currently a bit outdated)

**Comment by EclesioMeloJunior** [comment]
Hey @radkomih, instead of creating a new function I propose an update in the `NewTestInstanceWithTrie` to check if the `targetRuntime` argument is a valid file path if so we call `NewInstanceFromFile` otherwise we fetch it remotely, take a look in the following PR https://github.com/ChainSafe/gossamer/pull/3012.

This can be really helpful for testing as you're using  👍

**Comment by radkomih** [comment]
thanks!

**Comment by EclesioMeloJunior** [comment]
@radkomih fyi PR #3012 was merged!
