### ISSUE TITLE
Runtime calls are not working 

### ISSUE THREAD

**Issue by kanishkatn** [ChainSafe/gossamer#3217]
## Describe the bug

It looks like none of the runtime calls are working. I've tried it for all the chains on https://polkadot.js.org/apps by running the nodes locally. 

## Expected Behavior

Runtime calls shouldn't throw any errors.

## Current Behavior

Here's the response to some of the calls I tried
<img width="1725" alt="Screenshot 2023-04-19 at 1 25 05 PM" src="https://user-images.githubusercontent.com/4919645/233009325-7e2de15e-8880-456a-af35-53da79649bd8.png">

## To Reproduce
Steps to reproduce the behaviour:

1. Run a node `./bin/gossamer --chain westend --ws --ws-unsafe --ws-external --base-path ~/.gossamer/westend`
2. Go to https://polkadot.js.org/apps/#/runtime
3. Execute the runtime calls

## Specification

- go version: 1.20
- gossamer branch: `development`
- operating system: macOS

**Comment by jimjbrettj** [comment]
![image](https://user-images.githubusercontent.com/40345116/233729672-9db5760c-f98c-4ff8-9266-5ed125227b5e.png)

From what I have seen, this seems to be because we have not implemented the [state_call](https://github.com/ChainSafe/gossamer/blob/c6b459b26f49f94f5ac53ce773c2dff8dffe8fae/dot/rpc/modules/state.go#L249) method. See above logs for the behavior that I was seeing.

When we perform a call to state_call(core_version, 0x) we fail with this decoding issue, but when we add an actual value to pass is i.e. state_call(core_version, 0x0) we no longer get this error. 

So it seems to me that implementing state_call is the right path forward to fix this

**Comment by kanishkatn** [comment]
fixed in #3228
