### ISSUE TITLE
Failed to sync block `#11759946`: invalid memory address or nil pointer dereference (recovered by wazero)

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#3649]
## Describe the bug

- When Gossamer tries to import block `#11759946` it panics with `invalid memory address or nil pointer dereference`, but since this is a call managed by wazero the panic is recovered and returned as error

```
wasm stack trace: | 0273c3cd813a4ba7877099ce0c6f7420 | gossamer-westend
-- | -- | --
December 09, 2023 at 24:26 (UTC-4:00) | env.ext_storage_get_version_1(i64) i64 | 0273c3cd813a4ba7877099ce0c6f7420 | gossamer-westend
December 09, 2023 at 24:26 (UTC-4:00) | .sp_io::storage::extern_host_function_impls::get::h64f97d2167755354(i32,i32,i32) | 0273c3cd813a4ba7877099ce0c6f7420 | gossamer-westend
December 09, 2023 at 24:26 (UTC-4:00) | .frame_support::storage::unhashed::get_or_default::h6c7739c0a72a10b2(i32,i32) i32 | 0273c3cd813a4ba7877099ce0c6f7420 | gossamer-westend
December 09, 2023 at 24:26 (UTC-4:00) | .frame_support::storage::transactional::in_storage_layer::h890d5f5e450ca12e(i32,i32) | 0273c3cd813a4ba7877099ce0c6f7420 | gossamer-westend
December 09, 2023 at 24:26 (UTC-4:00) | .<pallet_nomination_pools::pallet::Call<T> as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h21608f5b92d65a21(i32,i32,i32) | 0273c3cd813a4ba7877099ce0c6f7420 | gossamer-westend
December 09, 2023 at 24:26 (UTC-4:00) | .<westend_runtime::Call as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h6d0f5d67d3fde819(i32,i32,i32) | 0273c3cd813a4ba7877099ce0c6f7420 | gossamer-westend
December 09, 2023 at 24:26 (UTC-4:00) | .<westend_runtime::Call as sp_runtime::traits::Dispatchable>::dispatch::h3d28764894ef20b5(i32,i32,i32) | 0273c3cd813a4ba7877099ce0c6f7420 | gossamer-westend
December 09, 2023 at 24:26 (UTC-4:00) | .<sp_runtime::generic::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra> as sp_runtime::traits::Applyable>::apply::h76a6b211044e6627(i32,i32,i32,i32) | 0273c3cd813a4ba7877099ce0c6f7420 | gossamer-westend
December 09, 2023 at 24:26 (UTC-4:00) | .frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::hc832cb517925aebc(i32,i32) | 0273c3cd813a4ba7877099ce0c6f7420 | gossamer-westend
December 09, 2023 at 24:26 (UTC-4:00) | .frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h65afa042e4cddf0e(i32) | 0273c3cd813a4ba7877099ce0c6f7420 | gossamer-westend
December 09, 2023 at 24:26 (UTC-4:00) | .Core_execute_block(i32,i32) i64 | 0273c3cd813a4ba7877099ce0c6f7420 | gossamer-westend
```

**Comment by jimjbrettj** [comment]
There are a few issues causing problems here. First, we are hitting a case where we call [RollbackStorageTransaction](https://github.com/ChainSafe/gossamer/blob/d57d37215f2cecfd89932294d11cbdc082a46b23/lib/runtime/storage/trie.go#L65) multiple times consecutively. This behavior is allowed by the protocol, however, we incorrectly set the `s.oldTrie` to nil, which means in the following function execution `t.trie` is set to nil. This behavior is not consistent with substrate and is causing our trie to be nil and panic.

Fixing this, however, does not solve all of our problems. For our `TrieState`, we hold references to the current trie as well as the previous trie and that is it. This becomes a problem because we need to be able to account for multiple transaction states simultaneously with the ability to rollback, where the current architecture can only support one at a time otherwise, it will incorrectly update past states and mess up the data. 

An example of a correct implementation is what kagome does, where they utilize a [transaction_stack](https://github.com/qdrvm/kagome/blob/fcedd31f7e0c060b001a82f06cfddbf2093cfb4a/core/runtime/common/trie_storage_provider_impl.hpp#L74) and a [base batch](https://github.com/qdrvm/kagome/blob/fcedd31f7e0c060b001a82f06cfddbf2093cfb4a/core/runtime/common/trie_storage_provider_impl.hpp#L77C29-L77C29).

A solution to this problem will involve refactoring gossamer code to be able to correctly process multiple transactions at once while maintaining data integrity.
