### ISSUE TITLE
Storage root mismatch at paseo block #1008649

### ISSUE THREAD

**Issue by jimjbrettj** [ChainSafe/gossamer#3943]
## Issue summary

- When we reach block #1008649 while syncing paseo, we are consistently hitting this critical case, as shown below in the logs, where the calculated storage root does not match the expected root.
- The cause if this needs to be investigated and this issue can be considered fix when the root calculations match and we are able to process this block and progress with syncing

## Other information and links

![image](https://github.com/ChainSafe/gossamer/assets/40345116/e259488e-1d98-42d9-8738-913c2f76147c)

**Comment by EclesioMeloJunior** [comment]
This error is happening due to a wrongly returned value in the `NextKey` trie method. If there is a current transaction happening and the runtime wants to get the next key we are actually returning the value that the desired next key holds instead of the next key itself.

<img width="337" alt="image" src="https://github.com/ChainSafe/gossamer/assets/17255488/20b228df-408e-4439-9666-b825aad669c3">
