### ISSUE TITLE
Design gap sync method

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#4201]
- [x] Define the components for Gap sync method
- [x] Understand the need and if it is closely related to Warp Sync or is a more general method
  - Yes, Gossamer will use the Gap sync strategy to fill the Gap left by Warp sync.
- [x] Create the issues/tasks for the implementation,
- https://github.com/paritytech/polkadot-sdk/blob/master/substrate/primitives/blockchain/src/backend.rs#L557

**Comment by EclesioMeloJunior** [comment]
# Gap sync
Gap sync is a method to fill gaps between blocks, for example: Warp sync is a method that retrieve specific block headers from the network with the goal to reach the tip of the chain quickly, however it leaves gaps in the chain that needs to be filled.

- Gap sync should run besides the other sync strategies given that it should not block warp sync neither full sync.
- Gap sync should store metadata about its progress in disk, like the latest gap or target block, enabling it to resume after a node hard stop or crash/panic.
- Gap sync should identify when it is done (when all gaps where filled) and stop working.


### Suggested approach

Gap sync should be a background running strategy with access to the chain state so it can import acquired blocks, also access to persist information to the disk.

This strategy can be placed in the `dot/sync/service.go`:
```go
// `dot/sync/service.go`

type SyncService struct { 
   ...
   gapSync Strategy
   ...
}
```

And we can spawn this background strategy in two ways:

#### First way

In the `func (s *SyncService) runSyncEngine()` we can read the disk to check if there is a ongoing gap sync work to resume:
```go
func (s *SyncService) runSyncEngine() {
   ...
   latestGap, err := s.gapSyncState.Retrieve()
   if err != nil {}
   if latestGap != nil {
        s.spawnGapSyncFrom(latestGap) 
   }
   ...
}
```
that will require an extra dependecy to the sync service which is `gapSyncState` that is responsible to write/read gap sync metadata informations, the `GapSyncState` can be placed at `dot/sync/gap_sync_state.go` and it will need to receive as argument the node `database.Database` and create a table with prefix `gapsync`, like we do at `dot/state/grandpa.go`, example: 
```go
func NewGrandpaStateFromGenesis(db database.Database, ...) {
    grandpaDB := database.NewTable(db, grandpaPrefix)
}
```

#### Second way

Here is where we will startup gap sync for the first time, the flow is:

```
1. We start the node for the first time
2. Warp sync is the current strategy and is running...
3. Warp sync reached the tip of the chain, but left a gap behind
4. Warp sync is finished, it will stop and switch to the default strategy which is FullSync
5. FullSync started and is running from the block where warp sync stopped and keep progressing...
6. We should start gap sync and place the target as the block warp sync stopped and full sync started...
```

The step 6 is the crucial point, when moving from `warp sync -> full sync` we should start the gap sync background process and place it the target it should achieve starting from genesis (or the `latestGap` see `First way`), once Gap Sync reaches the target it can just stop.

#### Internals of Gap Sync

The Gap sync strategy itself has an important information that is the `target` is should achieve to fill completely the gap left by warp sync, but in its internals it can progress in chunks of X blocks and once a chunk is retrieved and imported updates the `gap sync state` to hold valuable information in case of a hard stop or node crash panic, so when the node resumes gap sync can get back to the work as defined in `First way`.

**Comment by jimjbrettj** [comment]
One possible thing we could do here is instead of initiating gap sync only when warp sync is finished, we can issue it immediately as soon as the first gap is created. After that warp sync can constantly update the target for gap sync until it finishes, in which the target is stable from that point on. Since warp sync is faster than gap sync, warp sync will always stay ahead and both can run in parallel. This reduces the amount of time needed to "fill the gaps" once we are at the tip of the chain

**Comment by dimartiro** [comment]
I'll summarize some thoughts we discussed yesterday with @EclesioMeloJunior.

## Reusing the Full Sync Strategy

Our current full sync strategy is essentially a gap sync, as we request and download the gap between the blocks we have and the blocks we need. Therefore, we can reuse this same strategy to perform the gap sync instead of creating a separate process. The flow could look like this:

1. Start warp sync.
2. Warp sync completes.
3. Start state sync to retrieve the latest state (based on the previously retrieved block from warp sync).
4. State sync finishes.
5. Start full sync:
   - Handle new blocks based on block announcements.
   - Retrieve missing blocks in the gaps created by warp sync.

### Changes

- We will need a structure to track the gaps:
   - Support for stopping/resuming the node and being able to resume gap sync as well.
- We need to modify the current full sync logic:
   - `OnBlockAnnounce` - I think this could remain unchanged (@EclesioMeloJunior, what do you think?).
   - `NextActions` - We need to create gap sync requests here and add them to the actions list.
   - `Process` - We need to revisit this logic to ensure it doesn’t ignore the gap blocks.

**Comment by EclesioMeloJunior** [comment]
@dimartiro really good summarization. 
- Yes, the `OnBlockAnnounce` remain unchanged, since for the gap sync requests this is not important neither changes the behavior of filling gaps
- In `NextActions` we should always check if we filled the gap, so when we go from `State Sync Strategy` to `Full Sync Strategy` we should pass the gap target (block we need to achieve to fill the gap), we then we should check if we achieved such block, otherwise build the request to.
- `Process` will need to be smart enough to track 2 "heads" in the same chain. 
   - One head is the from the best blocks received in the block announces (these blocks are receive while we follow the tip) and we can process them because we know their parent.
   - The other head is from the gap sync, `Process` method should be able to retrieve and import the blocks knowing that they are "behind" the latest finalized block (since we are following the tip), but they are part of the canonical chain.
