### ISSUE TITLE
load name, id, protocol id, bootnodes from genesis upon startup

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#713]
currently, these are being set in config.toml, however they should be retrieved from the genesis file (with the LoadGenesisData function). we can add additional bootnodes in the config, or override the protocol ID in the config, but they should be loaded from the genesis data initially.

**Comment by ryanchristo** [comment]
Not sure this is a bug... The config.toml provides the base layer, we just need the genesis file properties to overwrite the confg if a specific genesis file is provided (the configuration in the genesis file and config.toml file should be the same otherwise.

**Comment by noot** [comment]
this is definitely a bug, the configuration for the chain comes from the genesis file. for example we shouldnt be able to overwrite chain name and ID and even protocol ID, these should be set in the genesis and never change.  

why would we need duplicate data in the genesis and the config? the only field I would consider duplicating/adding to from the config is the bootnodes.

**Comment by ryanchristo** [comment]
I guess I meant if the genesis property in the genesis file is provided. I think the toml configuration should still include all configuration parameters but the genesis file parameters should overwrite the toml configuration file parameters.

I was not sure if this was a bug because we have never used the parameters in the genesis file other than the raw data for the configuration but that's ok.
