### ISSUE TITLE
network: improve gossip algorithm by ensuring duplicate messages aren't sent to peers

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#738]
currently, the gossip algorithm is flooding, so sending the message to every peer except the one that it was received from. this should be improved as to reduce network bandwidth. one method of improving the gossip mechanism is to choose a number of peers to send the message to, say *n*, then randomly  select n peers out of our total peers. there are also other algorithms that could be used, will need some research and exploration. could make n configurable for now to determine *best* (ie. trade-off between bandwidth and propagation) value

**Comment by p4u** [comment]
Hello.
I am following your developments on Gossamer, you have a great base code which I think the global FOSS community might use.

We have been working on a similar approach, which is a libp2p Gossip based abstraction layer protocol which full fill the needs of most of the p2p blockchain-related projects. In our case we named it "subpub" (similar to PubSub) https://gitlab.com/vocdoni/go-dvote/-/tree/master/subpub

We are thinking on how to improve it and make it more resilient, efficient and smart. My background is on Mesh networks and I have been working on Dynamic Routing protocols for such networks. The problems we try to solve here are quite similar to that. On Mesh networks we have mainly two kind of dynamic routing protocols:

- link state (every node knows about the state of the whole network)
- distance vector (every node only knows its best direct neighbour to fetch a destination)

The second kind is the one that gives better results. Babel, Bmx7 and Batman-adv are three well known, widely used, routing protocols that use such mechanism.

So I would like to import the same principles on the blockchain p2p gossip layer. The basics would be something like:

1. A node uses the libp2p Kademlia DHT for boostraping (find nodes to connect)
2. Once a number of connections have been made (i.e 10 peers), disconnect from the DHT
3. Every node sends a very small packet (named Originator Message or OGM) to its neighbours which will be broadcasted to the whole network
4. With this mechanism all nodes know the existence of all nodes in the network
5. These OGMs are sent constantly by all nodes, i.e every 500ms and have a tracking number (1, 2, 3, 4....)
6. Node A will receive the same OGM (from B with the tracking number) probably by all its neighbours
7. Using the latency and packet loss node A will determine that the best way to reach B is through her neighbour C
8. This is done by all nodes, so every node will keep a table with a very simple relation: For reaching node X my best neighbour is Y
9. Once a packet is sent, it will reach its destination by the best path because every node will make its best choice.

This is a very simplified version on how this could work. More information here:

+ https://en.wikipedia.org/wiki/Distance-vector_routing_protocol
+ http://people.ac.upc.edu/leandro/pubs/semtor.pdf

If you are interested on developing something like this. We might try to join efforts on this task. If it is too far away from your ideas, then just ignore my petition.

Cheers

**Comment by noot** [comment]
this can be "pivoted" to be the gossiping of messages sent via notifications protocols

**Comment by noot** [comment]
also see spec 4.1.7.3: "Polkadot Host
implementers should implement a mechanism which only sends a transaction once to each peer and
avoids sending duplicates. Sending duplicate transactions might result in undefined consequences
such as being blocked for bad behavior by peers."

we need to ensure we aren't sending the duplicate messages to peers.
